package yawnlon.algorithms;

import java.util.*;

/**
 * Given two strings s and t which consist of only lowercase letters. String t
 * is generated by random shuffling string s and then add one more letter at a
 * random position. Find the letter that was added in t.
 * 
 * @author yawnlon
 *
 */

public class P389 {

	public static void main(String[] args) {
		System.out.println(findTheDifference("abcd", "abcde"));
	}

	public static char findTheDifference(String s, String t) {
		Map<Character, Integer> ms = getCharCount(s);
		Map<Character, Integer> ts = getCharCount(t);
		Iterator<Character> key = ts.keySet().iterator();
		while (key.hasNext()) {
			Character c = key.next();
			if (ms.get(c) == null || !ms.get(c).equals(ts.get(c))) {
				return c;
			}
		}
		return 0;
	}

	public static Map<Character, Integer> getCharCount(String s) {
		Map<Character, Integer> map = new HashMap<>();
		if (s != null) {
			for (int i = 0; i < s.length(); i++) {
				char c = s.charAt(i);
				if (map.get(c) == null) {
					map.put(c, 1);
				} else {
					map.put(c, map.get(c) + 1);
				}
			}
		}
		return map;
	}
}
